name: choose git push or pull CI
run-name: github push or CI
on: [push,pull_request]
jobs: 
  normal_ci: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: normal CI
        run: |
             echo pwd > ./a.sh
             chmod 777 ./a.sh
             ./a.sh
  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions\checkout@v4
      - name: pull_request
        run: |
             echo ls > ./b.sh
             chmod 777 ./a.sh
             ./b.sh
