name: choose git push or pull CI
run-name: github push or CI
on: [push,pull_request]
jobs: 
  normal-ci: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - name: normal CI
        run: pwd
  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions\checkout@v3
      - name: pull_request
        run: ls
