name: learn-github-action
run-name: ${{ github.actor }} is learning Github Actions
on:  
 workflow_dispatch: 
jobs: 
  check-bats-version: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
  run-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:    
        working-directory: ~/
    steps:
      - name: checkout the repository to the runner
        uses: action/checkout@v3
      - name: write a script
        run: echo -e '#!/bin/bash\npwd' >> testpwd.sh
      - name: privage
        run: chmod 777 ./testpwd.sh
      - name: run the script
        run: ./testpwd.sh
      - name: run the script
        run: ./my-other-script.sh
     