name: output file
run-name: ${{ github.actor }} output file to artifacts
on:    

  workflow_dispatch: 
jobs: 
  upload-job:
    runs-on: ubuntu-latest
    name: save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: upload output.log to artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: out-put-file
          path: output.log
  down-load:
    runs-on: ubuntu-latest
    needs: upload-job
    name: download file
    steps:
<<<<<<< HEAD
      - name: download files
        uses: actions/download-artifact@v3
        with: 
          name: out-put-file
=======
    - name: download output.log to artifacts
      uses: actions/download-artifact@v3
      with: 
        name: out-put-file
>>>>>>> b6892f442055e3603f682529fd0bf3e6f992241b

       
