on:
  issues: 
    types:
      - opened

jobs: 
  lable_issues:
    runs-on: ubuntu-latest
    steps: 
      - env: 
          GITHUB_TONKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        run: 
          gh issue edit $ISSUE_URL --add-label "triage"

    