on:
  workflow_dispatch:
env:
    # Setting an environment variable with the value of a configuration variable
    day_of_week: Monday 
  
jobs:
    display-variables:
      # You can use configuration variables with the `vars` context for dynamic jobs
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
      steps:
      - name: Use variables
        run: |
          echo "$Greeting $First_name. Today is $day_of_week"
        env:
          First_name: Chris

  