on:
  workflow_dispatch:
env:
    # Setting an environment variable with the value of a configuration variable
    day_of_week: Monday 
  
jobs:
    display-variables:
      # You can use configuration variables with the `vars` context for dynamic jobs
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
      steps:
      - name: Use variables
        run: |
          echo "$Greeting $First_name. Today is $day_of_week"
        env:
          First_name: Chris
    display-ifvar: 
      runs-on: ubuntu-latest
      env: 
        Greeting: Hello two
      steps: 
      - name: use if var run script
        if: ${{env.day_of_week == 'Monday'}}
        run: |
          echo "$Greeting $First_Name. Today is $day_of_week"
          echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.day_of_week }}!"
        env:
          First_Name: mike hi

  